// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect this MCP server with your Sincro account." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List the content dashboards (clients) that belong to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("clients").select("id, name, area, objectives, tone, audience, platforms").order("created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-content.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_content_default = defineTool2({
  name: "list_content",
  title: "List scheduled content",
  description: "List planned content items for the signed-in user, optionally filtered by client, status or date range (YYYY-MM-DD).",
  inputSchema: {
    client_id: z.string().optional().describe("Only return content for this client id."),
    status: z.string().optional().describe("Filter by status: draft, scheduled, published or idea."),
    from: z.string().optional().describe("Earliest date, YYYY-MM-DD."),
    to: z.string().optional().describe("Latest date, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, status, from, to }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("content_items").select("id, client_id, title, description, status, pillar, platform, date, time").order("date");
    if (client_id) query = query.eq("client_id", client_id);
    if (status) query = query.eq("status", status);
    if (from) query = query.gte("date", from);
    if (to) query = query.lte("date", to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_content_default = defineTool3({
  name: "create_content",
  title: "Create content item",
  description: "Schedule a new content item on a client's calendar for the signed-in user.",
  inputSchema: {
    client_id: z2.string().describe("Client id the content belongs to (see list_clients)."),
    title: z2.string().trim().min(1).describe("Content title."),
    description: z2.string().default("").describe("Short brief or copy for the post."),
    status: z2.enum(["draft", "scheduled", "published", "idea"]).default("draft").describe("Workflow status."),
    pillar: z2.enum(["educativo", "autoridade", "engajamento", "vendas", "bastidores"]).describe("Content pillar."),
    platform: z2.enum(["instagram", "linkedin", "tiktok", "youtube", "blog"]).describe("Target platform."),
    date: z2.string().describe("Publish date, YYYY-MM-DD."),
    time: z2.string().optional().describe("Publish time, HH:MM.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("content_items").insert({
      user_id: ctx.getUserId(),
      client_id: input.client_id,
      title: input.title,
      description: input.description ?? "",
      status: input.status ?? "draft",
      pillar: input.pillar,
      platform: input.platform,
      date: input.date,
      time: input.time || null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created content "${data.title}" on ${data.date}.` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list-ideas.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_ideas_default = defineTool4({
  name: "list_ideas",
  title: "List saved ideas",
  description: "List the ideas saved in the idea bank for the signed-in user.",
  inputSchema: {
    client_id: z3.string().optional().describe("Only return ideas for this client id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("ideas").select("id, client_id, title, description, pillar, format, hook").order("created_at");
    if (client_id) query = query.eq("client_id", client_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { ideas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-idea.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_idea_default = defineTool5({
  name: "create_idea",
  title: "Save idea",
  description: "Save a content idea to a client's idea bank for the signed-in user.",
  inputSchema: {
    client_id: z4.string().describe("Client id the idea belongs to (see list_clients)."),
    title: z4.string().trim().min(1).describe("Idea title."),
    description: z4.string().default("").describe("What the idea is about."),
    pillar: z4.enum(["educativo", "autoridade", "engajamento", "vendas", "bastidores"]).describe("Content pillar."),
    format: z4.string().default("").describe("Format, e.g. Reels, Carrossel, Artigo."),
    hook: z4.string().default("").describe("Opening hook for the content.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("ideas").insert({
      user_id: ctx.getUserId(),
      client_id: input.client_id,
      title: input.title,
      description: input.description ?? "",
      pillar: input.pillar,
      format: input.format ?? "",
      hook: input.hook ?? ""
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved idea "${data.title}".` }],
      structuredContent: { idea: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xaitymzbunmibcctvlrq";
var mcp_default = defineMcp({
  name: "sincro-mcp",
  title: "Sincro",
  version: "0.1.0",
  instructions: "Tools for Sincro, a multi-client content planning platform. Use `list_clients` to discover the signed-in user's client dashboards, then `list_content` / `create_content` for the editorial calendar and `list_ideas` / `create_idea` for the idea bank. Always pass a client_id from list_clients.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_content_default, create_content_default, list_ideas_default, create_idea_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
